### ISSUE TITLE
Site configuration

### ISSUE THREAD

**Issue by giuliov** [Getlatestversion/getlatestversion.eu-source#21]
- [ ] URL format: stick with `/:year/:month/:title/` ?
- [x] Comments enabled, default engine Discus, requires account ?
- [x] Google AD ID, same as YT channel ?
- [x] favicon
- [x] RSS feed
- [x] CNAME (in Hugo config)

**Comment by alkampfergit** [comment]
We should check if it is possible to have a discuss account shared between us, or where we can all be admin.
