### ISSUE TITLE
Define publish workflow

### ISSUE THREAD

**Issue by alkampfergit** [Getlatestversion/getlatestversion.eu-source#6]
- [x] use of `publishDate` (scheduled builds)
- [x] use of PR
- [ ] use of Netlify CMS

**Comment by alkampfergit** [comment]
Ho fatto una pr di esempio, di base dire
1. Fate una branch, magari con prefisso l'autore
1. fate li tutte le modifiche
1. Fate una pr verso master

esempio questa è la mia pr https://github.com/Getlatestversion/getlatestversion.eu-source/pull/4

**Comment by giuliov** [comment]
quello che dice @alkampfergit piu'

- PR obbligatoria su master
- @MattVSTS reviewer obbligatorio per l'inglese (opz @giuliov )
- almeno un altro Approver
- la PR viene approvata con squash merge

- Aggiungere rilancio su Twitter alla pubblicazione automatizzata (che scatta dopo il merge)
- prima o poi automatizzeremo altri rilanci (es. Facebook)

per convenzione ogni video su YouTube avra' un piccolo post pubblicitario

**Comment by giuliov** [comment]
@suxstellino suggerisce di avere sempre una Issue associata in modo da coordinarci le date di uscita
la data di uscita si imposta con il campo `publishDate` nel front-matter

**Comment by suxstellino** [comment]
Aggiungerei il tag per definire "pillola". Per ora l'ho messa nel titolo della issue.

**Comment by alkampfergit** [comment]
Allora, ho fatto un progetto https://github.com/Getlatestversion/getlatestversion.eu-source/projects/2 direttamente dove vorrei mettere l'organizzazione delle pillole, in questo modo possiamo non solo avere l'issue, ma anche iniziare a pianificare con gli altri

Quello che non so è se conviene avere un issue per una serie di pills, o tutti issue separati, in azure devops farei su due livelli ...

@suxstellino dovresti poter aggiungere anche tu il tag, per ora lo ho aggiunto io in verdino :D

**Comment by giuliov** [comment]
propose to create a separate issue for the CMS, in the [Enhancement project](https://github.com/Getlatestversion/getlatestversion.eu-source/projects/3) and close this one

**Comment by giuliov** [comment]
Closing. Remaining activity in https://github.com/Getlatestversion/getlatestversion.eu-source/projects/3#card-38335008
